const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  // User Management
  getUserInfo: () => ipcRenderer.invoke('get-user-info'),
  setAnonymousPresence: (active) => ipcRenderer.invoke('set-anonymous-presence', active === true),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  windowMinimize: () => ipcRenderer.invoke('window-minimize'),
  windowToggleMaximize: () => ipcRenderer.invoke('window-toggle-maximize'),
  getWindowState: () => ipcRenderer.invoke('get-window-state'),
  getGlobalCursorPosition: () => ipcRenderer.invoke('get-global-cursor-position'),
  getWindowGroupState: () => ipcRenderer.invoke('get-window-group-state'),
  setWindowActiveSection: (sectionId) => ipcRenderer.invoke('set-window-active-section', sectionId),
  windowClose: () => ipcRenderer.invoke('window-close'),
  login: (options = {}) => ipcRenderer.invoke('login', options),
  loginOffline: (username) => ipcRenderer.invoke('login-offline', username),
  logout: () => ipcRenderer.invoke('logout'),
  getAccounts: () => ipcRenderer.invoke('get-accounts'),
  switchAccount: (accountId) => ipcRenderer.invoke('switch-account', accountId),
  removeAccount: (accountId) => ipcRenderer.invoke('remove-account', accountId),
  getAuthConfig: () => ipcRenderer.invoke('get-auth-config'),
  setMicrosoftClientId: (clientId) => ipcRenderer.invoke('set-microsoft-client-id', clientId),
  getThemeConfig: () => ipcRenderer.invoke('get-theme-config'),
  setPrimaryColor: (primaryColor) => ipcRenderer.invoke('set-primary-color', primaryColor),
  setThemeMode: (themeMode) => ipcRenderer.invoke('set-theme-mode', themeMode),
  setAppearanceMode: (appearanceMode) => ipcRenderer.invoke('set-appearance-mode', appearanceMode),
  setBackgroundAnimation: (backgroundAnimation) => ipcRenderer.invoke('set-background-animation', backgroundAnimation),
  setLiveThemeColor: (primaryColor, appearanceMode) => ipcRenderer.invoke('set-live-theme-color', primaryColor, appearanceMode),
  getLanguageConfig: () => ipcRenderer.invoke('get-language-config'),
  setLanguagePreference: (languagePreference) => ipcRenderer.invoke('set-language-preference', languagePreference),
  openLauncherConfig: () => ipcRenderer.invoke('open-launcher-config'),
  openExternalUrl: (url) => ipcRenderer.invoke('open-external-url', url),
  openRouterSettings: (url) => ipcRenderer.invoke('open-router-settings', url),
  configureSwisscomPortForwarding: (options) => ipcRenderer.invoke('configure-swisscom-port-forwarding', options),
  checkAppUpdates: () => ipcRenderer.invoke('check-app-updates'),
  installAppUpdate: () => ipcRenderer.invoke('install-app-update'),
  checkServiceHealth: () => ipcRenderer.invoke('check-service-health'),

  // Minecraft & Fabric
  getMinecraftPath: () => ipcRenderer.invoke('get-minecraft-path'),
  chooseMinecraftPath: () => ipcRenderer.invoke('choose-minecraft-path'),
  getStandardModsPath: () => ipcRenderer.invoke('get-standard-mods-path'),
  chooseStandardModsPath: () => ipcRenderer.invoke('choose-standard-mods-path'),
  resetStandardModsPath: () => ipcRenderer.invoke('reset-standard-mods-path'),
  setMinecraftWindowsUserName: (windowsUserName) => ipcRenderer.invoke('set-minecraft-windows-user-name', windowsUserName),
  getLauncherStatus: () => ipcRenderer.invoke('get-launcher-status'),
  checkLauncherUpdates: () => ipcRenderer.invoke('check-launcher-updates'),
  getAvailableVersions: () => ipcRenderer.invoke('get-available-versions'),
  setSelectedVersion: (versionId) => ipcRenderer.invoke('set-selected-version', versionId),
  setStandardVersion: (versionId) => ipcRenderer.invoke('set-standard-version', versionId),
  downloadVersion: (versionId) => ipcRenderer.invoke('download-version', versionId),
  installFabric: () => ipcRenderer.invoke('install-fabric'),
  launchMinecraft: (username, accessToken, launchOptions = {}) => ipcRenderer.invoke('launch-minecraft', username, accessToken, launchOptions),
  getMinecraftRuntimeStatus: () => ipcRenderer.invoke('get-minecraft-runtime-status'),
  getServerFavorites: () => ipcRenderer.invoke('get-server-favorites'),
  addServerFavorite: (server) => ipcRenderer.invoke('add-server-favorite', server),
  removeServerFavorite: (serverId) => ipcRenderer.invoke('remove-server-favorite', serverId),
  getHostedServerStatus: () => ipcRenderer.invoke('get-hosted-server-status'),
  startHostedServer: (options) => ipcRenderer.invoke('start-hosted-server', options),
  stopHostedServer: (serverId) => ipcRenderer.invoke('stop-hosted-server', serverId),
  restartHostedServer: (options) => ipcRenderer.invoke('restart-hosted-server', options),
  sendHostedServerCommand: (serverId, command) => ipcRenderer.invoke('send-hosted-server-command', serverId, command),
  createHostedServer: (options) => ipcRenderer.invoke('create-hosted-server', options),
  saveHostedServer: (options) => ipcRenderer.invoke('save-hosted-server', options),
  selectHostedServer: (serverId) => ipcRenderer.invoke('select-hosted-server', serverId),
  deleteHostedServer: (serverId) => ipcRenderer.invoke('delete-hosted-server', serverId),
  importHostedServerMods: (filePaths) => ipcRenderer.invoke('import-hosted-server-mods', filePaths),
  installHostedServerModrinthMod: (project) => ipcRenderer.invoke('install-hosted-server-modrinth-mod', project),
  removeHostedServerMod: (fileName) => ipcRenderer.invoke('remove-hosted-server-mod', fileName),
  openHostedServerModsFolder: () => ipcRenderer.invoke('open-hosted-server-mods-folder'),
  openHostedServerFolder: () => ipcRenderer.invoke('open-hosted-server-folder'),
  saveOracleHostingCredentials: (credentials) => ipcRenderer.invoke('save-oracle-hosting-credentials', credentials),
  loginOracleCloud: (options = {}) => ipcRenderer.invoke('login-oracle-cloud', options),
  logoutOracleCloud: () => ipcRenderer.invoke('logout-oracle-cloud'),
  hostedServerVmAction: (serverId, action) => ipcRenderer.invoke('hosted-server-vm-action', serverId, action),
  configureDirectHosting: (serverId) => ipcRenderer.invoke('configure-direct-hosting', serverId),
  createHostedServerBackup: () => ipcRenderer.invoke('create-hosted-server-backup'),
  restoreHostedServerBackup: (fileName) => ipcRenderer.invoke('restore-hosted-server-backup', fileName),
  getPacks: () => ipcRenderer.invoke('get-packs'),
  createPack: (name, versionId) => ipcRenderer.invoke('create-pack', name, versionId),
  setActivePack: (packId) => ipcRenderer.invoke('set-active-pack', packId),
  deletePack: (packId) => ipcRenderer.invoke('delete-pack', packId),
  copyProfileSettings: (packId) => ipcRenderer.invoke('copy-profile-settings', packId),
  pasteProfileSettings: (packId) => ipcRenderer.invoke('paste-profile-settings', packId),

  // Mods
  getMods: () => ipcRenderer.invoke('get-mods'),
  getModsWithoutSync: () => ipcRenderer.invoke('get-mods-without-sync'),
  getInstalledModProjectIds: (versionId = '') => ipcRenderer.invoke('get-installed-mod-project-ids', versionId),
  searchModrinthMods: (query, versionId, projectType, offset = 0, limit = 100, forceRefresh = false) => ipcRenderer.invoke('search-modrinth-mods', query, versionId, projectType, offset, limit, forceRefresh),
  installModrinthMod: (project, target) => ipcRenderer.invoke('install-modrinth-mod', project, target),
  onModFolderChanged: (callback) => ipcRenderer.on('mod-folder-changed', (_event, payload) => callback(payload)),
  removeMod: (modId) => ipcRenderer.invoke('remove-mod', modId),
  removeIncompatibleMods: () => ipcRenderer.invoke('remove-incompatible-mods'),
  refreshMod: (modId) => ipcRenderer.invoke('refresh-mod', modId),
  setModEnabled: (modId, enabled) => ipcRenderer.invoke('set-mod-enabled', modId, enabled),
  importDroppedMods: (filePaths, options = {}) => ipcRenderer.invoke('import-dropped-mods', filePaths, options),
  getPathForFile: (file) => {
    if (webUtils?.getPathForFile) {
      return webUtils.getPathForFile(file);
    }
    return file?.path || '';
  },
  getSkinConfig: () => ipcRenderer.invoke('get-skin-config'),
  chooseSkinFile: () => ipcRenderer.invoke('choose-skin-file'),
  clearSkinFile: () => ipcRenderer.invoke('clear-skin-file'),
  setActiveSkin: (skinId) => ipcRenderer.invoke('set-active-skin', skinId),
  removeSkinFile: (skinId) => ipcRenderer.invoke('remove-skin-file', skinId),
  setSkinVariant: (skinId, variant) => ipcRenderer.invoke('set-skin-variant', skinId, variant),
  searchOnlineSkins: (query) => ipcRenderer.invoke('search-online-skins', query),
  downloadOnlineSkin: (onlineSkin) => ipcRenderer.invoke('download-online-skin', onlineSkin),
  loadModsFolder: () => ipcRenderer.invoke('load-mods-folder'),
  updateAllMods: () => ipcRenderer.invoke('update-all-mods'),
  cleanupNumberedAndDuplicateMods: () => ipcRenderer.invoke('cleanup-numbered-and-duplicate-mods'),
  getDebugMode: () => ipcRenderer.invoke('get-debug-mode'),
  runDiagnostics: () => ipcRenderer.invoke('run-diagnostics'),
  setDebugMode: (enabled) => ipcRenderer.invoke('set-debug-mode', enabled),
  openDiagnosticsFolder: () => ipcRenderer.invoke('open-diagnostics-folder'),

  // Events
  onWindowStateChanged: (callback) => ipcRenderer.on('window-state-changed', (_event, state) => callback(state)),
  onWindowGroupStateChanged: (callback) => ipcRenderer.on('window-group-state-changed', (_event, state) => callback(state)),
  onLauncherAppUpdateState: (callback) => ipcRenderer.on('launcher-app-update-state', (_event, state) => callback(state)),
  onGameEvent: (channel, callback) => ipcRenderer.on(channel, callback)
});
